name: Build CANN Image

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build.yml"
      - "cann/**"
      - "arg.json"

  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/build.yml"
      - "cann/**"
      - "arg.json"
      

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.get-build-target.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get build target
        id: get-build-target
        run: |
          TARGET_JSON=$(jq -c '{include: [.cann[].tags[0] | {target: .}]}' arg.json)
          echo "targets=$TARGET_JSON" >> $GITHUB_OUTPUT

  build:
    needs: prepare 
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix: 
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
        include:
          - arch: x86_64
            runner: linux_x86_64_wxs
          - arch: aarch64
            runner: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        id: build
        with: 
          platforms: ${{ matrix.arch }}
          file: ${{ github.workspace }}/cann/${{ matrix.target }}/Dockerfile
          context: ${{ github.workspace }}/cann/${{ matrix.target }}
          outputs: type=image

  
  


