name: Build CANN Images

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/docker.yml"
      - "cann/**"
      - "arg.json"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/docker.yml"
      - "cann/**"
      - "arg.json"
  release:
    types:
      - "published"

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          
          - name: "8.1.RC1.alpha001-910b-openeuler22.03-py3.10"
            context: "cann/8.1.RC1.alpha001-910b-openeuler22.03-py3.10"
            dockerfile: "Dockerfile"
            tags: ["docker.io/ascendai/cann:8.1.RC1.alpha001-910b-openeuler22.03-py3.10", "docker.io/ascendai/cann:openeuler-python3.10-cann8.1.RC1.alpha001", "quay.io/ascend/cann:8.1.RC1.alpha001-910b-openeuler22.03-py3.10", "quay.io/ascend/cann:openeuler-python3.10-cann8.1.RC1.alpha001", "swr.cn-southwest-2.myhuaweicloud.com/base_image/cann:8.1.RC1.alpha001-910b-openeuler22.03-py3.10", "swr.cn-southwest-2.myhuaweicloud.com/base_image/cann:openeuler-python3.10-cann8.1.RC1.alpha001", "swr.cn-east-3.myhuaweicloud.com/ascendhub-test/cann:8.1.RC1.alpha001-910b-openeuler22.03-py3.10"]
          
          - name: "8.1.RC1.alpha001-910b-ubuntu22.04-py3.10"
            context: "cann/8.1.RC1.alpha001-910b-ubuntu22.04-py3.10"
            dockerfile: "Dockerfile"
            tags: ["docker.io/ascendai/cann:8.1.RC1.alpha001-910b-ubuntu22.04-py3.10", "docker.io/ascendai/cann:8.1.RC1.alpha001", "docker.io/ascendai/cann:latest", "docker.io/ascendai/cann:ubuntu-python3.10-cann8.1.RC1.alpha001", "quay.io/ascend/cann:8.1.RC1.alpha001-910b-ubuntu22.04-py3.10", "quay.io/ascend/cann:8.1.RC1.alpha001", "quay.io/ascend/cann:latest", "quay.io/ascend/cann:ubuntu-python3.10-cann8.1.RC1.alpha001", "swr.cn-southwest-2.myhuaweicloud.com/base_image/cann:8.1.RC1.alpha001-910b-ubuntu22.04-py3.10", "swr.cn-southwest-2.myhuaweicloud.com/base_image/cann:8.1.RC1.alpha001", "swr.cn-southwest-2.myhuaweicloud.com/base_image/cann:latest", "swr.cn-southwest-2.myhuaweicloud.com/base_image/cann:ubuntu-python3.10-cann8.1.RC1.alpha001", "swr.cn-east-3.myhuaweicloud.com/ascendhub-test/cann:8.1.RC1.alpha001-910b-ubuntu22.04-py3.10"]
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to AscendHub
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v3
        with:
          registry: swr.cn-east-3.myhuaweicloud.com
          username: ${{ secrets.ASCENDHUB_USERNAME }}
          password: ${{ secrets.ASCENDHUB_TOKEN }}

      - name: Login to DockerHub
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to Quay
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Login to OpenMind
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v3
        with:
          registry: swr.cn-southwest-2.myhuaweicloud.com
          username: ${{ secrets.OPENMIND_USERNAME }}
          password: ${{ secrets.OPENMIND_TOKEN }}

      - name: Login to ghcr.io
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,key=${{ runner.os }}-buildx-${{ matrix.context }}
          cache-to: type=gha,mode=max,key=${{ runner.os }}-buildx-${{ matrix.context }}
          context: ${{ github.workspace }}/{{ matrix.context }}
          file: ${{ github.workspace }}/{{ matrix.context }}/${{ matrix.dockerfile }}
          tags: ${{ matrix.tags | join(',') }}
          push: ${{ github.event_name == 'release' }}

      - name: Show space
        if: ${{ always() }}
        shell: bash
        run: |
          set -x
          df -h
          docker images -a
