name: Build CANN Images

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/docker.yml"
      - "cann/**"
      - "arg.json"
      - "docker-bake.hcl"
  release:
    types:
      - "published"

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-target.outputs.targets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List targets
        id: list-target
        uses: docker/bake-action/subaction/list-targets@v6
        with:
          files: |
            arg.json
            docker-bake.hcl

  push-readme:
    name: Push README
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push README to DockerHub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_TOKEN }}
        with:
          destination_container_repo: ascendai/cann
          provider: dockerhub
          readme_file: 'README.md'

      - name: Push README to Quay.io
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_APIKEY: ${{ secrets.APIKEY__QUAY_IO }}
        with:
          destination_container_repo: quay.io/ascend/cann
          provider: quay
          readme_file: 'README.md'
