name: Main (Build/Publish)

on:
  workflow_call:
    inputs:
      target_name:
        description: 'name of the build target'
        required: true
        type: string
      context:
        description: 'path to the build context'
        required: true
        type: string
      dockerfile:
        description: 'file name of the Dockerfile'
        required: true
        type: string
      repos:
        description: 'name of the repositories'
        required: true
        type: string
      ascendhub_repo:
        description: 'name of the AscendHub repository'
        required: true
        type: string
      common_registry_tags:
        description: 'tags of the common registry'
        required: true
        type: string
      ascendhub_registry_tags:
        description: 'tags of the AscendHub registry'
        required: true
        type: string
      event_name:
        description: 'name of the event that triggered the workflow'
        required: true
        type: string

    secrets:
      DOCKER_USERNAME:
        description: 'Username of the DockerHub registry'
        required: true
      DOCKER_TOKEN:
        description: 'Token of the DockerHub registry'
        required: true
      ASCENDHUB_USERNAME:
        description: 'Username of the AscendHub registry'
        required: true
      ASCENDHUB_TOKEN:
        description: 'Token of the AscendHub registry'
        required: true
      
jobs:
  push-ascendhub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to AscendHub
        uses: docker/login-action@v3
        with:
          registry: swr.cn-east-3.myhuaweicloud.com
          username: ${{ secrets.ASCENDHUB_USERNAME }}
          password: ${{ secrets.ASCENDHUB_TOKEN }}
          ecr: false
          logout: false

      - name: Push to AscendHub
        run: |
            COMMON_TAGS_ARRAY=($(echo "${{ inputs.common_registry_tags }}" | sed '/^$/d'))
            ASCENDHUB_TAGS_ARRAY=($(echo "${{ inputs.ascendhub_registry_tags }}" | sed '/^$/d'))
            SOURCE_IMAGE="docker.io/ascendai/cann"
            SOURCE_TAG="${COMMON_TAGS_ARRAY[0]#*:}"

            TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${SOURCE_IMAGE#docker.io/}:pull" | jq -r .token)
            
            MANIFEST_LIST=$(curl -s \
            -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" \
            -H "Authorization: Bearer $TOKEN" \
            "https://registry-1.docker.io/v2/${SOURCE_IMAGE#docker.io/}/manifests/$SOURCE_TAG")
            DIGESTS=()

            for ARCH in "amd64" "arm64"; do
              DIGEST=$(echo "$MANIFEST_LIST" | jq -r --arg arch "$ARCH" '.manifests[] | select(.platform.architecture == $arch) | .digest')
              if [ -n "$DIGEST" ]; then
                DIGESTS+=("$SOURCE_IMAGE@$DIGEST")
              fi
            done

            for TAG in "${ASCENDHUB_TAGS_ARRAY[@]}"; do
              echo "Pushing $TAG with ${#DIGESTS[@]} architectures..."
              docker buildx imagetools create \
                --tag "$TAG" \
                "${DIGESTS[@]}"
            done

