on:
  workflow_call:
    inputs:
      target_name:
        required: true
        type: string
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      repos:
        required: true
        type: string
      ascendhub_repo:
        required: true
        type: string
      common_registry_tags:
        required: true
        type: string
      ascendhub_registry_tags:
        required: true
        type: string

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true
      ASCENDHUB_USERNAME:
        required: true
      ASCENDHUB_TOKEN:
        required: true
      
jobs:
  build-cann:
    runs-on: ${{ matrix.runner }}
    strategy:
        matrix:
          include:
            - arch: x86_64
              runner: linux-x86_64
            - arch: aarch64
              runner: linux-aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          ecr: false
          logout: false

      - name: Login to DockerHub
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          ecr: false
          logout: false

      - name: Build and push by digest
        uses: docker/build-push-action@v6
        id: build
        with: 
          platforms: ${{ matrix.arch }}
          tags: ${{ inputs.repos }}
          file: ${{ github.workspace }}/${{ inputs.context }}/${{ inputs.dockerfile }}
          context: ${{ github.workspace }}/${{ inputs.context }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ inputs.target_name }}-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  push-cann:
    runs-on: ubuntu-latest
    needs: build-cann
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-${{ inputs.target_name }}-*
          merge-multiple: true

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          ecr: false
          logout: false
      
      - name: Login to DockerHub
        if: ${{ github.event_name == 'release' }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          ecr: false
          logout: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
            TAGS_ARRAY=($(echo "${{ inputs.common_registry_tags }}" | sed '/^$/d'))
            for TAG in "${TAGS_ARRAY[@]}"; do
              docker buildx imagetools create -t "$TAG" \
                $(printf 'quay.io/ascend/cann@sha256:%s ' *)
            done
      
  push-ascendhub:
    runs-on: ubuntu-latest
    needs: push-cann
    steps:
      - name: Login to AscendHub
        uses: docker/login-action@v3
        with:
          registry: swr.cn-east-3.myhuaweicloud.com
          username: ${{ secrets.ASCENDHUB_USERNAME }}
          password: ${{ secrets.ASCENDHUB_TOKEN }}
          ecr: false
          logout: false

      - name: Push to AscendHub
        run: |
            COMMON_TAGS_ARRAY=($(echo "${{ inputs.common_registry_tags }}" | sed '/^$/d'))
            ASCENDHUB_TAGS_ARRAY=($(echo "${{ inputs.ascendhub_registry_tags }}" | sed '/^$/d'))
            docker pull "${COMMON_TAGS_ARRAY[0]}"
            for TAG in "${ASCENDHUB_TAGS_ARRAY[@]}"; do
              docker tag "${COMMON_TAGS_ARRAY[0]}" "${TAG}"
              docker push "${TAG}"
            done
  


      

